### ISSUE TITLE
Perfil da Localização por id

### ISSUE THREAD

**Issue by LuciBustamante** [luanaxcardoso/ExerciciosAPIs_Squad_MaryJackson#3]
#### Orientações:

Criar uma nova rota para exibir o perfil da localização. 
A rota deverá ser acessível através do caminho /location/<id>. 
A página deverá ser renderizada através do template location.html. 
A página deverá conter as seguintes informações: nome, tipo, dimensão e uma lista com os personagens que aparecem na localização. 
A lista deverá conter um link para a página de perfil do personagem.

> Doc API: https://rickandmortyapi.com/documentation/#rest

**Comment by luanaxcardoso** [comment]
Em andamento.
