### ISSUE TITLE
Perfil do Episódio por id

### ISSUE THREAD

**Issue by LuciBustamante** [luanaxcardoso/ExerciciosAPIs_Squad_MaryJackson#4]
#### Orientações:

Criar uma nova rota para exibir o perfil do episódio. 
A rota deverá ser acessível através do caminho /episode/<id>. 
A página deverá ser renderizada através do template episode.html. 
A página deverá conter as seguintes informações: nome, data de lançamento, código e uma lista com os personagens que aparecem no episódio. 
A lista deverá conter um link para a página de perfil do personagem.

> Doc API: https://rickandmortyapi.com/documentation/#rest

**Comment by tainatravassos** [comment]
Feito!
